### ISSUE TITLE
Results are empty

### ISSUE THREAD

**Issue by s7nkuridza** [gsouf/google-url#17]
It seems Google changed structure, so this library is not working as before (master branch).
From example:
$simpsonPage1->getPositions() // return empty array
$simpsonPage1->getNaturals() // return empty object
$simpsonPage1->getAdword() // is working

**Comment by gsouf** [comment]
Hello,

We just fixed an issue a few says ago : https://github.com/gsouf/google-url/issues/15

Did you update to the latest version ?

**Comment by s7nkuridza** [comment]
Yes I forgot to update repo, thanks for response, this issue can be closed.

**Comment by kaushikkavi** [comment]
Hello,

I have same issue results are empty and adWord works fine. Can you tell me where is wrong . It works fine yesterday but suddenly it stop working today.

I have natural query like NATURAL_QUERY="//div[@id = 'ires']/ol/descendant::*[self::div or self::li][@class='g']";

i download latest repo but still not working.

Plz suggest.

**Comment by gsouf** [comment]
Ansewred
